version: '3.8'

services:
  wiki-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your API keys here for local testing
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Optional: mount local env file for testing
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wiki-chat-network

  # Optional: Add a simple nginx reverse proxy for testing external access
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wiki-chat
    restart: unless-stopped
    networks:
      - wiki-chat-network
    profiles:
      - proxy

networks:
  wiki-chat-network:
    driver: bridge

# Usage examples:
#
# Local development testing:
# docker-compose up --build
#
# With nginx proxy:
# docker-compose --profile proxy up --build
#
# Build only:
# docker-compose build
#
# Run in background:
# docker-compose up -d
#
# View logs:
# docker-compose logs -f wiki-chat
#
# Stop and cleanup:
# docker-compose down