apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-chat
  namespace: knowledge-quest
  labels:
    app: kids-multi-wiki-chat
    version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: kids-multi-wiki-chat
  template:
    metadata:
      labels:
        app: kids-multi-wiki-chat
        version: v1.0.0
    spec:
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: wiki-chat
        image: ghcr.io/joerawr/kids-multi-wiki-chat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_LOCKED_MODEL
          value: "gemini-2.5-flash"
        - name: GOOGLE_GENERATIVE_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: wiki-chat-secrets
              key: google-generative-ai-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: wiki-chat-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
---
